name: GoHome
version: 1.3.9
main: de.raizcookie.gohome.main.Main
api-version: 1.13

commands:
   home:
      description: Teleports you to your home!
   delhome:
      description: Removes your home!
   sethome: 
      description: Places a home!